/*
 * This source file was generated by the Gradle 'init' task
 */
package semantic_core;

public class JSC {
    public static void main(String[] args) {
        System.out.println("START");

        try {
            Structurizer.start();
        } catch (StructException e) {
            e.printStackTrace();
        }
    }
}
